name: Missile-Fighter
version: 1.0.0

scripts:
  build:
    - echo "Building the Missile-Fighter project..."
    - pnpm install
    - echo "Build completed."

  start:
    - echo "Starting the Missile-Fighter server..."
    - pnpm run dev

  clean:
    - echo "Cleaning the project..."
    - rm -rf node_modules
    - echo "Clean completed."

dependencies:
  - node
  - pnpm

steps:
  - name: Install dependencies
    run: pnpm install

  - name: Build the project
    run: pnpm run build

  - name: Start the server
    run: pnpm run start